[[edge_functions]]
  path = "/test"
  function = "geolocation"

[[redirects]]
  from = "/test/:name.svg"
  to = "https://juan-edge-function-test.netlify.app/test/:name.svg"
  status = 200

[[redirects]]
  from = "/test/_next/*"
  to = "https://juan-edge-function-test.netlify.app/test/_next/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "https://juanpb96.github.io/:splat"
  status = 200
  force = true

