[[redirects]]
  from = "/test/*"
  to = "https://juanbonilla-fem-weather-app.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "https://juanpb96.github.io/:splat"
  status = 200